export default {
  BAACode: 'NzRiODgyNjhkZDNjNGNmZThkZTFiZGM2NjdjNDE2ODY6IGRIT2d1MGZjTWlqb2FnMjZwdUZjMVJEVXlVNG5PaDhObHlCaGNBakY=',
  clientId: '74b88268dd3c4cfe8de1bdc667c41686',
  secretKey: 'dHOgu0fcMijoag26puFc1RDUyU4nOh8NlyBhcAjF',
  ESI_URL: 'https://esi.tech.ccp.is/latest',
  callback: 'http://localhost:10407/callback/',
  scopes: [
    'publicData',
    'characterStatsRead',
    'characterFittingsRead',
    'characterFittingsWrite',
    'characterLocationRead',
    'characterWalletRead',
    'characterAssetsRead',
    'characterKillsRead',
    'characterMailRead',
    'characterMarketOrdersRead',
    'characterMedalsRead',
    'characterNotificationsRead',
    'characterSkillsRead',
    'characterAccountRead',
    'characterClonesRead',
    'esi-mail.read_mail.v1',
    'esi-characters.read_fatigue.v1',
    'esi-location.read_location.v1',
    'esi-universe.read_structures.v1',
    'esi-wallet.read_character_wallet.v1',
  ],
};
